# Sync configuration (optional)
# sync_address = "https://api.atuin.sh"
# sync_frequency = "10m"

# UI settings
style = "compact"
show_preview = true
show_help = false

# Search settings
search_mode = "fuzzy"
filter_mode = "global"
filter_mode_shell_up_key_binding = "session"

# Behavior
update_check = false
sync_enabled = false  # Enable if you want cloud sync
