-- Original nvim-treesitter (main branch, requires 0.12)
require('nvim-treesitter').setup({
  ensure_installed = {
    'lua',
    'python',
    'javascript',
    'typescript',
    'tsx',
    'go',
    'gomod',
    'gosum',
    'html',
    'css',
    'json',
    'yaml',
    'toml',
    'markdown',
    'markdown_inline',
    'bash',
    'templ',
    'vim',
    'vimdoc',
    'regex',
    'diff',
  },
  highlight = { enable = true },
  indent = { enable = true },
})
