"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$host\
$directory\
$git_branch\
$git_status\
$fill\
$package\
$golang\
$lua\
$nvim\
$nodejs\
$python\
$rust\
$elixir\
$dart\
$aws\
$time\
$cmd_duration
$character\
"""

[fill]
symbol = " "

[username]
format = " [╭─$user]($style)@"
style_user = "bold purple"
style_root = "bold purple"
show_always = true

[hostname]
format = "[$hostname]($style) "
style = "bold purple"
trim_at = "-"
ssh_only = false
disabled = false

[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "󰳏 "

[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[cmd_duration]
min_time = 1
style = "white"
format = "[$duration]($style)"
disabled = false

[time]
format = " 🕙 $time($style)"
time_format = "%T"
style = "bright-white"

[character]
success_symbol = " [╰─ ](bold purple)"
error_symbol = " [×](bold red)"

[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[aws]
symbol = "  "
format = '[$symbol($profile)(\[$duration\] )]($style)'

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
format = "[$symbol$context]($style) "
style = "blue"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
format = '[$symbol$branch ]($style)'

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = "λ "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
#pyenv_version_name = true
format = '[${symbol}(${version})(\($virtualenv\) )]($style)'
style = "bold blue"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
symbol = " " 
format = "[$symbol$version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
